name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "ver/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: 'gradle'

      - name: Configure Git
        run: git config --global user.email "action@github.com" && git config --global user.name "Github Action"

      - name: Apply patches
        run: ./gradlew applyPatches --stacktrace

      - name: Build Paperclip Jar
        run: ./gradlew createMojmapPaperclipJar --stacktrace

      - name: Upload Paperclip Jar
        uses: actions/upload-artifact@v4
        with:
          name: linearpaper
          path: build/libs/linearpaper-paperclip-*-mojmap.jar
